site_name: wdl-docs
theme:
  name: readthedocs
  include_homepage_in_sidebar: true
  navigation_depth: 4

nav:
  - Home: 'index.md'
  - 'WDL Plumbing':
    - 'Base structure': 'Base_structure.md'
    - 'Conditionals': 'conditionals.md'
